services:
  fleetdb:
    image: ghcr.io/metal-automata/fleetdb:latest
    depends_on:
      - postgresql
      - fleetdb-migrate
    environment:
      - FLEETDB_OIDC_ENABLED=false
      - FLEETDB_CRDB_URI=${PG_DSN:?"expected postgresql DB URI env var"}  #postgresql://postgres@postgresql:5432/fleetdb?sslmode=disable
      - FLEETDB_DB_ENCRYPTION_DRIVER=base64key://smGbjm71Nxd1Ig5FS0wj9SlbzAIrnolCz9bQQ6uAhl4=
    ports:
      - "127.0.0.1:8000:8000"
    restart: unless-stopped
    networks:
      - automata

  fleetdb-migrate:
    image: ghcr.io/metal-automata/fleetdb:latest
    command:
      migrate up
    depends_on:
      - postgresql
    environment:
      - FLEETDB_CRDB_URI=${PG_DSN:?"expected postgresql DB URI env var"} #postgresql://postgres@postgresql:5432/postgres?sslmode=disable
    restart: on-failure
    networks:
      - automata

  postgresql:
    image: postgres:17.0-alpine3.20
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"
    restart: unless-stopped
    networks:
      - automata

volumes:
  db:

networks:
  automata:
