wipe = true
pkgname = "models"
output = "internal/models"
strict-verify-mod-version = true

[psql]
dbname = "fleetdb_test"
host = "localhost"
port = 5432
user = "fleetdb_test"
sslmode = "disable"
blacklist = ["goose_db_version"]
