// Code generated by SQLBoiler 4.15.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testComponentStatuses(t *testing.T) {
	t.Parallel()

	query := ComponentStatuses()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testComponentStatusesDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ComponentStatus{}
	if err = randomize.Struct(seed, o, componentStatusDBTypes, true, componentStatusColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ComponentStatus struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := ComponentStatuses().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testComponentStatusesQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ComponentStatus{}
	if err = randomize.Struct(seed, o, componentStatusDBTypes, true, componentStatusColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ComponentStatus struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := ComponentStatuses().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := ComponentStatuses().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testComponentStatusesSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ComponentStatus{}
	if err = randomize.Struct(seed, o, componentStatusDBTypes, true, componentStatusColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ComponentStatus struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := ComponentStatusSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := ComponentStatuses().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testComponentStatusesExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ComponentStatus{}
	if err = randomize.Struct(seed, o, componentStatusDBTypes, true, componentStatusColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ComponentStatus struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := ComponentStatusExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if ComponentStatus exists: %s", err)
	}
	if !e {
		t.Errorf("Expected ComponentStatusExists to return true, but got false.")
	}
}

func testComponentStatusesFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ComponentStatus{}
	if err = randomize.Struct(seed, o, componentStatusDBTypes, true, componentStatusColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ComponentStatus struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	componentStatusFound, err := FindComponentStatus(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if componentStatusFound == nil {
		t.Error("want a record, got nil")
	}
}

func testComponentStatusesBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ComponentStatus{}
	if err = randomize.Struct(seed, o, componentStatusDBTypes, true, componentStatusColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ComponentStatus struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = ComponentStatuses().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testComponentStatusesOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ComponentStatus{}
	if err = randomize.Struct(seed, o, componentStatusDBTypes, true, componentStatusColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ComponentStatus struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := ComponentStatuses().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testComponentStatusesAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	componentStatusOne := &ComponentStatus{}
	componentStatusTwo := &ComponentStatus{}
	if err = randomize.Struct(seed, componentStatusOne, componentStatusDBTypes, false, componentStatusColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ComponentStatus struct: %s", err)
	}
	if err = randomize.Struct(seed, componentStatusTwo, componentStatusDBTypes, false, componentStatusColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ComponentStatus struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = componentStatusOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = componentStatusTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := ComponentStatuses().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testComponentStatusesCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	componentStatusOne := &ComponentStatus{}
	componentStatusTwo := &ComponentStatus{}
	if err = randomize.Struct(seed, componentStatusOne, componentStatusDBTypes, false, componentStatusColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ComponentStatus struct: %s", err)
	}
	if err = randomize.Struct(seed, componentStatusTwo, componentStatusDBTypes, false, componentStatusColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ComponentStatus struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = componentStatusOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = componentStatusTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := ComponentStatuses().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func componentStatusBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *ComponentStatus) error {
	*o = ComponentStatus{}
	return nil
}

func componentStatusAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *ComponentStatus) error {
	*o = ComponentStatus{}
	return nil
}

func componentStatusAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *ComponentStatus) error {
	*o = ComponentStatus{}
	return nil
}

func componentStatusBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *ComponentStatus) error {
	*o = ComponentStatus{}
	return nil
}

func componentStatusAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *ComponentStatus) error {
	*o = ComponentStatus{}
	return nil
}

func componentStatusBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *ComponentStatus) error {
	*o = ComponentStatus{}
	return nil
}

func componentStatusAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *ComponentStatus) error {
	*o = ComponentStatus{}
	return nil
}

func componentStatusBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *ComponentStatus) error {
	*o = ComponentStatus{}
	return nil
}

func componentStatusAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *ComponentStatus) error {
	*o = ComponentStatus{}
	return nil
}

func testComponentStatusesHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &ComponentStatus{}
	o := &ComponentStatus{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, componentStatusDBTypes, false); err != nil {
		t.Errorf("Unable to randomize ComponentStatus object: %s", err)
	}

	AddComponentStatusHook(boil.BeforeInsertHook, componentStatusBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	componentStatusBeforeInsertHooks = []ComponentStatusHook{}

	AddComponentStatusHook(boil.AfterInsertHook, componentStatusAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	componentStatusAfterInsertHooks = []ComponentStatusHook{}

	AddComponentStatusHook(boil.AfterSelectHook, componentStatusAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	componentStatusAfterSelectHooks = []ComponentStatusHook{}

	AddComponentStatusHook(boil.BeforeUpdateHook, componentStatusBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	componentStatusBeforeUpdateHooks = []ComponentStatusHook{}

	AddComponentStatusHook(boil.AfterUpdateHook, componentStatusAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	componentStatusAfterUpdateHooks = []ComponentStatusHook{}

	AddComponentStatusHook(boil.BeforeDeleteHook, componentStatusBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	componentStatusBeforeDeleteHooks = []ComponentStatusHook{}

	AddComponentStatusHook(boil.AfterDeleteHook, componentStatusAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	componentStatusAfterDeleteHooks = []ComponentStatusHook{}

	AddComponentStatusHook(boil.BeforeUpsertHook, componentStatusBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	componentStatusBeforeUpsertHooks = []ComponentStatusHook{}

	AddComponentStatusHook(boil.AfterUpsertHook, componentStatusAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	componentStatusAfterUpsertHooks = []ComponentStatusHook{}
}

func testComponentStatusesInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ComponentStatus{}
	if err = randomize.Struct(seed, o, componentStatusDBTypes, true, componentStatusColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ComponentStatus struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := ComponentStatuses().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testComponentStatusesInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ComponentStatus{}
	if err = randomize.Struct(seed, o, componentStatusDBTypes, true); err != nil {
		t.Errorf("Unable to randomize ComponentStatus struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(componentStatusColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := ComponentStatuses().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testComponentStatusToOneServerComponentUsingServerComponent(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local ComponentStatus
	var foreign ServerComponent

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, componentStatusDBTypes, false, componentStatusColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ComponentStatus struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, serverComponentDBTypes, false, serverComponentColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ServerComponent struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.ServerComponentID = foreign.ID
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.ServerComponent().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.ID != foreign.ID {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	ranAfterSelectHook := false
	AddServerComponentHook(boil.AfterSelectHook, func(ctx context.Context, e boil.ContextExecutor, o *ServerComponent) error {
		ranAfterSelectHook = true
		return nil
	})

	slice := ComponentStatusSlice{&local}
	if err = local.L.LoadServerComponent(ctx, tx, false, (*[]*ComponentStatus)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.ServerComponent == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.ServerComponent = nil
	if err = local.L.LoadServerComponent(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.ServerComponent == nil {
		t.Error("struct should have been eager loaded")
	}

	if !ranAfterSelectHook {
		t.Error("failed to run AfterSelect hook for relationship")
	}
}

func testComponentStatusToOneSetOpServerComponentUsingServerComponent(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a ComponentStatus
	var b, c ServerComponent

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, componentStatusDBTypes, false, strmangle.SetComplement(componentStatusPrimaryKeyColumns, componentStatusColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, serverComponentDBTypes, false, strmangle.SetComplement(serverComponentPrimaryKeyColumns, serverComponentColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, serverComponentDBTypes, false, strmangle.SetComplement(serverComponentPrimaryKeyColumns, serverComponentColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*ServerComponent{&b, &c} {
		err = a.SetServerComponent(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.ServerComponent != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.ComponentStatus != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.ServerComponentID != x.ID {
			t.Error("foreign key was wrong value", a.ServerComponentID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.ServerComponentID))
		reflect.Indirect(reflect.ValueOf(&a.ServerComponentID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.ServerComponentID != x.ID {
			t.Error("foreign key was wrong value", a.ServerComponentID, x.ID)
		}
	}
}

func testComponentStatusesReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ComponentStatus{}
	if err = randomize.Struct(seed, o, componentStatusDBTypes, true, componentStatusColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ComponentStatus struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testComponentStatusesReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ComponentStatus{}
	if err = randomize.Struct(seed, o, componentStatusDBTypes, true, componentStatusColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ComponentStatus struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := ComponentStatusSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testComponentStatusesSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ComponentStatus{}
	if err = randomize.Struct(seed, o, componentStatusDBTypes, true, componentStatusColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ComponentStatus struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := ComponentStatuses().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	componentStatusDBTypes = map[string]string{`ID`: `uuid`, `ServerComponentID`: `uuid`, `Health`: `text`, `State`: `text`, `Info`: `text`, `CreatedAt`: `timestamp with time zone`, `UpdatedAt`: `timestamp with time zone`}
	_                      = bytes.MinRead
)

func testComponentStatusesUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(componentStatusPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(componentStatusAllColumns) == len(componentStatusPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &ComponentStatus{}
	if err = randomize.Struct(seed, o, componentStatusDBTypes, true, componentStatusColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ComponentStatus struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := ComponentStatuses().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, componentStatusDBTypes, true, componentStatusPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize ComponentStatus struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testComponentStatusesSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(componentStatusAllColumns) == len(componentStatusPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &ComponentStatus{}
	if err = randomize.Struct(seed, o, componentStatusDBTypes, true, componentStatusColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ComponentStatus struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := ComponentStatuses().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, componentStatusDBTypes, true, componentStatusPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize ComponentStatus struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(componentStatusAllColumns, componentStatusPrimaryKeyColumns) {
		fields = componentStatusAllColumns
	} else {
		fields = strmangle.SetComplement(
			componentStatusAllColumns,
			componentStatusPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := ComponentStatusSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testComponentStatusesUpsert(t *testing.T) {
	t.Parallel()

	if len(componentStatusAllColumns) == len(componentStatusPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := ComponentStatus{}
	if err = randomize.Struct(seed, &o, componentStatusDBTypes, true); err != nil {
		t.Errorf("Unable to randomize ComponentStatus struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert ComponentStatus: %s", err)
	}

	count, err := ComponentStatuses().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, componentStatusDBTypes, false, componentStatusPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize ComponentStatus struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert ComponentStatus: %s", err)
	}

	count, err = ComponentStatuses().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
