// Code generated by SQLBoiler 4.15.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testComponentCapabilities(t *testing.T) {
	t.Parallel()

	query := ComponentCapabilities()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testComponentCapabilitiesDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ComponentCapability{}
	if err = randomize.Struct(seed, o, componentCapabilityDBTypes, true, componentCapabilityColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ComponentCapability struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := ComponentCapabilities().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testComponentCapabilitiesQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ComponentCapability{}
	if err = randomize.Struct(seed, o, componentCapabilityDBTypes, true, componentCapabilityColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ComponentCapability struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := ComponentCapabilities().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := ComponentCapabilities().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testComponentCapabilitiesSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ComponentCapability{}
	if err = randomize.Struct(seed, o, componentCapabilityDBTypes, true, componentCapabilityColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ComponentCapability struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := ComponentCapabilitySlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := ComponentCapabilities().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testComponentCapabilitiesExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ComponentCapability{}
	if err = randomize.Struct(seed, o, componentCapabilityDBTypes, true, componentCapabilityColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ComponentCapability struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := ComponentCapabilityExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if ComponentCapability exists: %s", err)
	}
	if !e {
		t.Errorf("Expected ComponentCapabilityExists to return true, but got false.")
	}
}

func testComponentCapabilitiesFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ComponentCapability{}
	if err = randomize.Struct(seed, o, componentCapabilityDBTypes, true, componentCapabilityColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ComponentCapability struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	componentCapabilityFound, err := FindComponentCapability(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if componentCapabilityFound == nil {
		t.Error("want a record, got nil")
	}
}

func testComponentCapabilitiesBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ComponentCapability{}
	if err = randomize.Struct(seed, o, componentCapabilityDBTypes, true, componentCapabilityColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ComponentCapability struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = ComponentCapabilities().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testComponentCapabilitiesOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ComponentCapability{}
	if err = randomize.Struct(seed, o, componentCapabilityDBTypes, true, componentCapabilityColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ComponentCapability struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := ComponentCapabilities().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testComponentCapabilitiesAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	componentCapabilityOne := &ComponentCapability{}
	componentCapabilityTwo := &ComponentCapability{}
	if err = randomize.Struct(seed, componentCapabilityOne, componentCapabilityDBTypes, false, componentCapabilityColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ComponentCapability struct: %s", err)
	}
	if err = randomize.Struct(seed, componentCapabilityTwo, componentCapabilityDBTypes, false, componentCapabilityColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ComponentCapability struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = componentCapabilityOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = componentCapabilityTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := ComponentCapabilities().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testComponentCapabilitiesCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	componentCapabilityOne := &ComponentCapability{}
	componentCapabilityTwo := &ComponentCapability{}
	if err = randomize.Struct(seed, componentCapabilityOne, componentCapabilityDBTypes, false, componentCapabilityColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ComponentCapability struct: %s", err)
	}
	if err = randomize.Struct(seed, componentCapabilityTwo, componentCapabilityDBTypes, false, componentCapabilityColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ComponentCapability struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = componentCapabilityOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = componentCapabilityTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := ComponentCapabilities().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func componentCapabilityBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *ComponentCapability) error {
	*o = ComponentCapability{}
	return nil
}

func componentCapabilityAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *ComponentCapability) error {
	*o = ComponentCapability{}
	return nil
}

func componentCapabilityAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *ComponentCapability) error {
	*o = ComponentCapability{}
	return nil
}

func componentCapabilityBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *ComponentCapability) error {
	*o = ComponentCapability{}
	return nil
}

func componentCapabilityAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *ComponentCapability) error {
	*o = ComponentCapability{}
	return nil
}

func componentCapabilityBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *ComponentCapability) error {
	*o = ComponentCapability{}
	return nil
}

func componentCapabilityAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *ComponentCapability) error {
	*o = ComponentCapability{}
	return nil
}

func componentCapabilityBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *ComponentCapability) error {
	*o = ComponentCapability{}
	return nil
}

func componentCapabilityAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *ComponentCapability) error {
	*o = ComponentCapability{}
	return nil
}

func testComponentCapabilitiesHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &ComponentCapability{}
	o := &ComponentCapability{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, componentCapabilityDBTypes, false); err != nil {
		t.Errorf("Unable to randomize ComponentCapability object: %s", err)
	}

	AddComponentCapabilityHook(boil.BeforeInsertHook, componentCapabilityBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	componentCapabilityBeforeInsertHooks = []ComponentCapabilityHook{}

	AddComponentCapabilityHook(boil.AfterInsertHook, componentCapabilityAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	componentCapabilityAfterInsertHooks = []ComponentCapabilityHook{}

	AddComponentCapabilityHook(boil.AfterSelectHook, componentCapabilityAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	componentCapabilityAfterSelectHooks = []ComponentCapabilityHook{}

	AddComponentCapabilityHook(boil.BeforeUpdateHook, componentCapabilityBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	componentCapabilityBeforeUpdateHooks = []ComponentCapabilityHook{}

	AddComponentCapabilityHook(boil.AfterUpdateHook, componentCapabilityAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	componentCapabilityAfterUpdateHooks = []ComponentCapabilityHook{}

	AddComponentCapabilityHook(boil.BeforeDeleteHook, componentCapabilityBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	componentCapabilityBeforeDeleteHooks = []ComponentCapabilityHook{}

	AddComponentCapabilityHook(boil.AfterDeleteHook, componentCapabilityAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	componentCapabilityAfterDeleteHooks = []ComponentCapabilityHook{}

	AddComponentCapabilityHook(boil.BeforeUpsertHook, componentCapabilityBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	componentCapabilityBeforeUpsertHooks = []ComponentCapabilityHook{}

	AddComponentCapabilityHook(boil.AfterUpsertHook, componentCapabilityAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	componentCapabilityAfterUpsertHooks = []ComponentCapabilityHook{}
}

func testComponentCapabilitiesInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ComponentCapability{}
	if err = randomize.Struct(seed, o, componentCapabilityDBTypes, true, componentCapabilityColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ComponentCapability struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := ComponentCapabilities().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testComponentCapabilitiesInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ComponentCapability{}
	if err = randomize.Struct(seed, o, componentCapabilityDBTypes, true); err != nil {
		t.Errorf("Unable to randomize ComponentCapability struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(componentCapabilityColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := ComponentCapabilities().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testComponentCapabilityToOneServerComponentUsingServerComponent(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local ComponentCapability
	var foreign ServerComponent

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, componentCapabilityDBTypes, false, componentCapabilityColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ComponentCapability struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, serverComponentDBTypes, false, serverComponentColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ServerComponent struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.ServerComponentID = foreign.ID
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.ServerComponent().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.ID != foreign.ID {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	ranAfterSelectHook := false
	AddServerComponentHook(boil.AfterSelectHook, func(ctx context.Context, e boil.ContextExecutor, o *ServerComponent) error {
		ranAfterSelectHook = true
		return nil
	})

	slice := ComponentCapabilitySlice{&local}
	if err = local.L.LoadServerComponent(ctx, tx, false, (*[]*ComponentCapability)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.ServerComponent == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.ServerComponent = nil
	if err = local.L.LoadServerComponent(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.ServerComponent == nil {
		t.Error("struct should have been eager loaded")
	}

	if !ranAfterSelectHook {
		t.Error("failed to run AfterSelect hook for relationship")
	}
}

func testComponentCapabilityToOneSetOpServerComponentUsingServerComponent(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a ComponentCapability
	var b, c ServerComponent

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, componentCapabilityDBTypes, false, strmangle.SetComplement(componentCapabilityPrimaryKeyColumns, componentCapabilityColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, serverComponentDBTypes, false, strmangle.SetComplement(serverComponentPrimaryKeyColumns, serverComponentColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, serverComponentDBTypes, false, strmangle.SetComplement(serverComponentPrimaryKeyColumns, serverComponentColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*ServerComponent{&b, &c} {
		err = a.SetServerComponent(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.ServerComponent != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.ComponentCapabilities[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.ServerComponentID != x.ID {
			t.Error("foreign key was wrong value", a.ServerComponentID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.ServerComponentID))
		reflect.Indirect(reflect.ValueOf(&a.ServerComponentID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.ServerComponentID != x.ID {
			t.Error("foreign key was wrong value", a.ServerComponentID, x.ID)
		}
	}
}

func testComponentCapabilitiesReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ComponentCapability{}
	if err = randomize.Struct(seed, o, componentCapabilityDBTypes, true, componentCapabilityColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ComponentCapability struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testComponentCapabilitiesReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ComponentCapability{}
	if err = randomize.Struct(seed, o, componentCapabilityDBTypes, true, componentCapabilityColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ComponentCapability struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := ComponentCapabilitySlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testComponentCapabilitiesSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ComponentCapability{}
	if err = randomize.Struct(seed, o, componentCapabilityDBTypes, true, componentCapabilityColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ComponentCapability struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := ComponentCapabilities().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	componentCapabilityDBTypes = map[string]string{`ID`: `uuid`, `ServerComponentID`: `uuid`, `Name`: `text`, `Description`: `text`, `Enabled`: `boolean`, `CreatedAt`: `timestamp with time zone`, `UpdatedAt`: `timestamp with time zone`}
	_                          = bytes.MinRead
)

func testComponentCapabilitiesUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(componentCapabilityPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(componentCapabilityAllColumns) == len(componentCapabilityPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &ComponentCapability{}
	if err = randomize.Struct(seed, o, componentCapabilityDBTypes, true, componentCapabilityColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ComponentCapability struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := ComponentCapabilities().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, componentCapabilityDBTypes, true, componentCapabilityPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize ComponentCapability struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testComponentCapabilitiesSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(componentCapabilityAllColumns) == len(componentCapabilityPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &ComponentCapability{}
	if err = randomize.Struct(seed, o, componentCapabilityDBTypes, true, componentCapabilityColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ComponentCapability struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := ComponentCapabilities().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, componentCapabilityDBTypes, true, componentCapabilityPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize ComponentCapability struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(componentCapabilityAllColumns, componentCapabilityPrimaryKeyColumns) {
		fields = componentCapabilityAllColumns
	} else {
		fields = strmangle.SetComplement(
			componentCapabilityAllColumns,
			componentCapabilityPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := ComponentCapabilitySlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testComponentCapabilitiesUpsert(t *testing.T) {
	t.Parallel()

	if len(componentCapabilityAllColumns) == len(componentCapabilityPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := ComponentCapability{}
	if err = randomize.Struct(seed, &o, componentCapabilityDBTypes, true); err != nil {
		t.Errorf("Unable to randomize ComponentCapability struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert ComponentCapability: %s", err)
	}

	count, err := ComponentCapabilities().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, componentCapabilityDBTypes, false, componentCapabilityPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize ComponentCapability struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert ComponentCapability: %s", err)
	}

	count, err = ComponentCapabilities().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
