// Code generated by SQLBoiler 4.15.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/null/v8"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// ComponentCapability is an object representing the database table.
type ComponentCapability struct {
	ID                string      `boil:"id" json:"id" toml:"id" yaml:"id"`
	ServerComponentID string      `boil:"server_component_id" json:"server_component_id" toml:"server_component_id" yaml:"server_component_id"`
	Name              string      `boil:"name" json:"name" toml:"name" yaml:"name"`
	Description       null.String `boil:"description" json:"description,omitempty" toml:"description" yaml:"description,omitempty"`
	Enabled           null.Bool   `boil:"enabled" json:"enabled,omitempty" toml:"enabled" yaml:"enabled,omitempty"`
	CreatedAt         null.Time   `boil:"created_at" json:"created_at,omitempty" toml:"created_at" yaml:"created_at,omitempty"`
	UpdatedAt         null.Time   `boil:"updated_at" json:"updated_at,omitempty" toml:"updated_at" yaml:"updated_at,omitempty"`

	R *componentCapabilityR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L componentCapabilityL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var ComponentCapabilityColumns = struct {
	ID                string
	ServerComponentID string
	Name              string
	Description       string
	Enabled           string
	CreatedAt         string
	UpdatedAt         string
}{
	ID:                "id",
	ServerComponentID: "server_component_id",
	Name:              "name",
	Description:       "description",
	Enabled:           "enabled",
	CreatedAt:         "created_at",
	UpdatedAt:         "updated_at",
}

var ComponentCapabilityTableColumns = struct {
	ID                string
	ServerComponentID string
	Name              string
	Description       string
	Enabled           string
	CreatedAt         string
	UpdatedAt         string
}{
	ID:                "component_capabilities.id",
	ServerComponentID: "component_capabilities.server_component_id",
	Name:              "component_capabilities.name",
	Description:       "component_capabilities.description",
	Enabled:           "component_capabilities.enabled",
	CreatedAt:         "component_capabilities.created_at",
	UpdatedAt:         "component_capabilities.updated_at",
}

// Generated where

type whereHelpernull_Bool struct{ field string }

func (w whereHelpernull_Bool) EQ(x null.Bool) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, false, x)
}
func (w whereHelpernull_Bool) NEQ(x null.Bool) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, true, x)
}
func (w whereHelpernull_Bool) LT(x null.Bool) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpernull_Bool) LTE(x null.Bool) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpernull_Bool) GT(x null.Bool) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpernull_Bool) GTE(x null.Bool) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}

func (w whereHelpernull_Bool) IsNull() qm.QueryMod    { return qmhelper.WhereIsNull(w.field) }
func (w whereHelpernull_Bool) IsNotNull() qm.QueryMod { return qmhelper.WhereIsNotNull(w.field) }

var ComponentCapabilityWhere = struct {
	ID                whereHelperstring
	ServerComponentID whereHelperstring
	Name              whereHelperstring
	Description       whereHelpernull_String
	Enabled           whereHelpernull_Bool
	CreatedAt         whereHelpernull_Time
	UpdatedAt         whereHelpernull_Time
}{
	ID:                whereHelperstring{field: "\"component_capabilities\".\"id\""},
	ServerComponentID: whereHelperstring{field: "\"component_capabilities\".\"server_component_id\""},
	Name:              whereHelperstring{field: "\"component_capabilities\".\"name\""},
	Description:       whereHelpernull_String{field: "\"component_capabilities\".\"description\""},
	Enabled:           whereHelpernull_Bool{field: "\"component_capabilities\".\"enabled\""},
	CreatedAt:         whereHelpernull_Time{field: "\"component_capabilities\".\"created_at\""},
	UpdatedAt:         whereHelpernull_Time{field: "\"component_capabilities\".\"updated_at\""},
}

// ComponentCapabilityRels is where relationship names are stored.
var ComponentCapabilityRels = struct {
	ServerComponent string
}{
	ServerComponent: "ServerComponent",
}

// componentCapabilityR is where relationships are stored.
type componentCapabilityR struct {
	ServerComponent *ServerComponent `boil:"ServerComponent" json:"ServerComponent" toml:"ServerComponent" yaml:"ServerComponent"`
}

// NewStruct creates a new relationship struct
func (*componentCapabilityR) NewStruct() *componentCapabilityR {
	return &componentCapabilityR{}
}

func (r *componentCapabilityR) GetServerComponent() *ServerComponent {
	if r == nil {
		return nil
	}
	return r.ServerComponent
}

// componentCapabilityL is where Load methods for each relationship are stored.
type componentCapabilityL struct{}

var (
	componentCapabilityAllColumns            = []string{"id", "server_component_id", "name", "description", "enabled", "created_at", "updated_at"}
	componentCapabilityColumnsWithoutDefault = []string{"server_component_id", "name"}
	componentCapabilityColumnsWithDefault    = []string{"id", "description", "enabled", "created_at", "updated_at"}
	componentCapabilityPrimaryKeyColumns     = []string{"id"}
	componentCapabilityGeneratedColumns      = []string{}
)

type (
	// ComponentCapabilitySlice is an alias for a slice of pointers to ComponentCapability.
	// This should almost always be used instead of []ComponentCapability.
	ComponentCapabilitySlice []*ComponentCapability
	// ComponentCapabilityHook is the signature for custom ComponentCapability hook methods
	ComponentCapabilityHook func(context.Context, boil.ContextExecutor, *ComponentCapability) error

	componentCapabilityQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	componentCapabilityType                 = reflect.TypeOf(&ComponentCapability{})
	componentCapabilityMapping              = queries.MakeStructMapping(componentCapabilityType)
	componentCapabilityPrimaryKeyMapping, _ = queries.BindMapping(componentCapabilityType, componentCapabilityMapping, componentCapabilityPrimaryKeyColumns)
	componentCapabilityInsertCacheMut       sync.RWMutex
	componentCapabilityInsertCache          = make(map[string]insertCache)
	componentCapabilityUpdateCacheMut       sync.RWMutex
	componentCapabilityUpdateCache          = make(map[string]updateCache)
	componentCapabilityUpsertCacheMut       sync.RWMutex
	componentCapabilityUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var componentCapabilityAfterSelectHooks []ComponentCapabilityHook

var componentCapabilityBeforeInsertHooks []ComponentCapabilityHook
var componentCapabilityAfterInsertHooks []ComponentCapabilityHook

var componentCapabilityBeforeUpdateHooks []ComponentCapabilityHook
var componentCapabilityAfterUpdateHooks []ComponentCapabilityHook

var componentCapabilityBeforeDeleteHooks []ComponentCapabilityHook
var componentCapabilityAfterDeleteHooks []ComponentCapabilityHook

var componentCapabilityBeforeUpsertHooks []ComponentCapabilityHook
var componentCapabilityAfterUpsertHooks []ComponentCapabilityHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *ComponentCapability) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range componentCapabilityAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *ComponentCapability) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range componentCapabilityBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *ComponentCapability) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range componentCapabilityAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *ComponentCapability) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range componentCapabilityBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *ComponentCapability) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range componentCapabilityAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *ComponentCapability) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range componentCapabilityBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *ComponentCapability) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range componentCapabilityAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *ComponentCapability) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range componentCapabilityBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *ComponentCapability) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range componentCapabilityAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddComponentCapabilityHook registers your hook function for all future operations.
func AddComponentCapabilityHook(hookPoint boil.HookPoint, componentCapabilityHook ComponentCapabilityHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		componentCapabilityAfterSelectHooks = append(componentCapabilityAfterSelectHooks, componentCapabilityHook)
	case boil.BeforeInsertHook:
		componentCapabilityBeforeInsertHooks = append(componentCapabilityBeforeInsertHooks, componentCapabilityHook)
	case boil.AfterInsertHook:
		componentCapabilityAfterInsertHooks = append(componentCapabilityAfterInsertHooks, componentCapabilityHook)
	case boil.BeforeUpdateHook:
		componentCapabilityBeforeUpdateHooks = append(componentCapabilityBeforeUpdateHooks, componentCapabilityHook)
	case boil.AfterUpdateHook:
		componentCapabilityAfterUpdateHooks = append(componentCapabilityAfterUpdateHooks, componentCapabilityHook)
	case boil.BeforeDeleteHook:
		componentCapabilityBeforeDeleteHooks = append(componentCapabilityBeforeDeleteHooks, componentCapabilityHook)
	case boil.AfterDeleteHook:
		componentCapabilityAfterDeleteHooks = append(componentCapabilityAfterDeleteHooks, componentCapabilityHook)
	case boil.BeforeUpsertHook:
		componentCapabilityBeforeUpsertHooks = append(componentCapabilityBeforeUpsertHooks, componentCapabilityHook)
	case boil.AfterUpsertHook:
		componentCapabilityAfterUpsertHooks = append(componentCapabilityAfterUpsertHooks, componentCapabilityHook)
	}
}

// One returns a single componentCapability record from the query.
func (q componentCapabilityQuery) One(ctx context.Context, exec boil.ContextExecutor) (*ComponentCapability, error) {
	o := &ComponentCapability{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for component_capabilities")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all ComponentCapability records from the query.
func (q componentCapabilityQuery) All(ctx context.Context, exec boil.ContextExecutor) (ComponentCapabilitySlice, error) {
	var o []*ComponentCapability

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to ComponentCapability slice")
	}

	if len(componentCapabilityAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all ComponentCapability records in the query.
func (q componentCapabilityQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count component_capabilities rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q componentCapabilityQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if component_capabilities exists")
	}

	return count > 0, nil
}

// ServerComponent pointed to by the foreign key.
func (o *ComponentCapability) ServerComponent(mods ...qm.QueryMod) serverComponentQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.ServerComponentID),
	}

	queryMods = append(queryMods, mods...)

	return ServerComponents(queryMods...)
}

// LoadServerComponent allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (componentCapabilityL) LoadServerComponent(ctx context.Context, e boil.ContextExecutor, singular bool, maybeComponentCapability interface{}, mods queries.Applicator) error {
	var slice []*ComponentCapability
	var object *ComponentCapability

	if singular {
		var ok bool
		object, ok = maybeComponentCapability.(*ComponentCapability)
		if !ok {
			object = new(ComponentCapability)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeComponentCapability)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeComponentCapability))
			}
		}
	} else {
		s, ok := maybeComponentCapability.(*[]*ComponentCapability)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeComponentCapability)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeComponentCapability))
			}
		}
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &componentCapabilityR{}
		}
		args = append(args, object.ServerComponentID)

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &componentCapabilityR{}
			}

			for _, a := range args {
				if a == obj.ServerComponentID {
					continue Outer
				}
			}

			args = append(args, obj.ServerComponentID)

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`server_components`),
		qm.WhereIn(`server_components.id in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load ServerComponent")
	}

	var resultSlice []*ServerComponent
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice ServerComponent")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for server_components")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for server_components")
	}

	if len(serverComponentAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.ServerComponent = foreign
		if foreign.R == nil {
			foreign.R = &serverComponentR{}
		}
		foreign.R.ComponentCapabilities = append(foreign.R.ComponentCapabilities, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.ServerComponentID == foreign.ID {
				local.R.ServerComponent = foreign
				if foreign.R == nil {
					foreign.R = &serverComponentR{}
				}
				foreign.R.ComponentCapabilities = append(foreign.R.ComponentCapabilities, local)
				break
			}
		}
	}

	return nil
}

// SetServerComponent of the componentCapability to the related item.
// Sets o.R.ServerComponent to related.
// Adds o to related.R.ComponentCapabilities.
func (o *ComponentCapability) SetServerComponent(ctx context.Context, exec boil.ContextExecutor, insert bool, related *ServerComponent) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"component_capabilities\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"server_component_id"}),
		strmangle.WhereClause("\"", "\"", 2, componentCapabilityPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.ServerComponentID = related.ID
	if o.R == nil {
		o.R = &componentCapabilityR{
			ServerComponent: related,
		}
	} else {
		o.R.ServerComponent = related
	}

	if related.R == nil {
		related.R = &serverComponentR{
			ComponentCapabilities: ComponentCapabilitySlice{o},
		}
	} else {
		related.R.ComponentCapabilities = append(related.R.ComponentCapabilities, o)
	}

	return nil
}

// ComponentCapabilities retrieves all the records using an executor.
func ComponentCapabilities(mods ...qm.QueryMod) componentCapabilityQuery {
	mods = append(mods, qm.From("\"component_capabilities\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"component_capabilities\".*"})
	}

	return componentCapabilityQuery{q}
}

// FindComponentCapability retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindComponentCapability(ctx context.Context, exec boil.ContextExecutor, iD string, selectCols ...string) (*ComponentCapability, error) {
	componentCapabilityObj := &ComponentCapability{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"component_capabilities\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, componentCapabilityObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from component_capabilities")
	}

	if err = componentCapabilityObj.doAfterSelectHooks(ctx, exec); err != nil {
		return componentCapabilityObj, err
	}

	return componentCapabilityObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *ComponentCapability) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no component_capabilities provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if queries.MustTime(o.CreatedAt).IsZero() {
			queries.SetScanner(&o.CreatedAt, currTime)
		}
		if queries.MustTime(o.UpdatedAt).IsZero() {
			queries.SetScanner(&o.UpdatedAt, currTime)
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(componentCapabilityColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	componentCapabilityInsertCacheMut.RLock()
	cache, cached := componentCapabilityInsertCache[key]
	componentCapabilityInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			componentCapabilityAllColumns,
			componentCapabilityColumnsWithDefault,
			componentCapabilityColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(componentCapabilityType, componentCapabilityMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(componentCapabilityType, componentCapabilityMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"component_capabilities\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"component_capabilities\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into component_capabilities")
	}

	if !cached {
		componentCapabilityInsertCacheMut.Lock()
		componentCapabilityInsertCache[key] = cache
		componentCapabilityInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the ComponentCapability.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *ComponentCapability) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		queries.SetScanner(&o.UpdatedAt, currTime)
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	componentCapabilityUpdateCacheMut.RLock()
	cache, cached := componentCapabilityUpdateCache[key]
	componentCapabilityUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			componentCapabilityAllColumns,
			componentCapabilityPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update component_capabilities, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"component_capabilities\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, componentCapabilityPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(componentCapabilityType, componentCapabilityMapping, append(wl, componentCapabilityPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update component_capabilities row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for component_capabilities")
	}

	if !cached {
		componentCapabilityUpdateCacheMut.Lock()
		componentCapabilityUpdateCache[key] = cache
		componentCapabilityUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q componentCapabilityQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for component_capabilities")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for component_capabilities")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o ComponentCapabilitySlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), componentCapabilityPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"component_capabilities\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, componentCapabilityPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in componentCapability slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all componentCapability")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *ComponentCapability) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no component_capabilities provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if queries.MustTime(o.CreatedAt).IsZero() {
			queries.SetScanner(&o.CreatedAt, currTime)
		}
		queries.SetScanner(&o.UpdatedAt, currTime)
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(componentCapabilityColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	componentCapabilityUpsertCacheMut.RLock()
	cache, cached := componentCapabilityUpsertCache[key]
	componentCapabilityUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			componentCapabilityAllColumns,
			componentCapabilityColumnsWithDefault,
			componentCapabilityColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			componentCapabilityAllColumns,
			componentCapabilityPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert component_capabilities, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(componentCapabilityPrimaryKeyColumns))
			copy(conflict, componentCapabilityPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"component_capabilities\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(componentCapabilityType, componentCapabilityMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(componentCapabilityType, componentCapabilityMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert component_capabilities")
	}

	if !cached {
		componentCapabilityUpsertCacheMut.Lock()
		componentCapabilityUpsertCache[key] = cache
		componentCapabilityUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single ComponentCapability record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *ComponentCapability) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no ComponentCapability provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), componentCapabilityPrimaryKeyMapping)
	sql := "DELETE FROM \"component_capabilities\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from component_capabilities")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for component_capabilities")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q componentCapabilityQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no componentCapabilityQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from component_capabilities")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for component_capabilities")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o ComponentCapabilitySlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(componentCapabilityBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), componentCapabilityPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"component_capabilities\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, componentCapabilityPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from componentCapability slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for component_capabilities")
	}

	if len(componentCapabilityAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *ComponentCapability) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindComponentCapability(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *ComponentCapabilitySlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := ComponentCapabilitySlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), componentCapabilityPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"component_capabilities\".* FROM \"component_capabilities\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, componentCapabilityPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in ComponentCapabilitySlice")
	}

	*o = slice

	return nil
}

// ComponentCapabilityExists checks if the ComponentCapability row exists.
func ComponentCapabilityExists(ctx context.Context, exec boil.ContextExecutor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"component_capabilities\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if component_capabilities exists")
	}

	return exists, nil
}

// Exists checks if the ComponentCapability row exists.
func (o *ComponentCapability) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return ComponentCapabilityExists(ctx, exec, o.ID)
}
