// Code generated by SQLBoiler 4.15.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("AocMacAddresses", testAocMacAddressesUpsert)

	t.Run("Attributes", testAttributesUpsert)

	t.Run("AttributesFirmwareSets", testAttributesFirmwareSetsUpsert)

	t.Run("BiosConfigComponents", testBiosConfigComponentsUpsert)

	t.Run("BiosConfigSets", testBiosConfigSetsUpsert)

	t.Run("BiosConfigSettings", testBiosConfigSettingsUpsert)

	t.Run("BMCMacAddresses", testBMCMacAddressesUpsert)

	t.Run("BomInfos", testBomInfosUpsert)

	t.Run("ComponentCapabilities", testComponentCapabilitiesUpsert)

	t.Run("ComponentChangeReports", testComponentChangeReportsUpsert)

	t.Run("ComponentFirmwareSets", testComponentFirmwareSetsUpsert)

	t.Run("ComponentFirmwareSetMaps", testComponentFirmwareSetMapsUpsert)

	t.Run("ComponentFirmwareVersions", testComponentFirmwareVersionsUpsert)

	t.Run("ComponentMetadata", testComponentMetadataUpsert)

	t.Run("ComponentStatuses", testComponentStatusesUpsert)

	t.Run("EventHistories", testEventHistoriesUpsert)

	t.Run("FirmwareSetValidationFacts", testFirmwareSetValidationFactsUpsert)

	t.Run("HardwareModels", testHardwareModelsUpsert)

	t.Run("HardwareVendors", testHardwareVendorsUpsert)

	t.Run("InstalledFirmwares", testInstalledFirmwaresUpsert)

	t.Run("ServerBMCS", testServerBMCSUpsert)

	t.Run("ServerComponentTypes", testServerComponentTypesUpsert)

	t.Run("ServerComponents", testServerComponentsUpsert)

	t.Run("ServerCredentialTypes", testServerCredentialTypesUpsert)

	t.Run("ServerCredentials", testServerCredentialsUpsert)

	t.Run("ServerStatuses", testServerStatusesUpsert)

	t.Run("Servers", testServersUpsert)

	t.Run("VersionedAttributes", testVersionedAttributesUpsert)
}
