// Code generated by SQLBoiler 4.15.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testServerStatuses(t *testing.T) {
	t.Parallel()

	query := ServerStatuses()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testServerStatusesDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ServerStatus{}
	if err = randomize.Struct(seed, o, serverStatusDBTypes, true, serverStatusColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ServerStatus struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := ServerStatuses().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testServerStatusesQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ServerStatus{}
	if err = randomize.Struct(seed, o, serverStatusDBTypes, true, serverStatusColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ServerStatus struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := ServerStatuses().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := ServerStatuses().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testServerStatusesSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ServerStatus{}
	if err = randomize.Struct(seed, o, serverStatusDBTypes, true, serverStatusColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ServerStatus struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := ServerStatusSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := ServerStatuses().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testServerStatusesExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ServerStatus{}
	if err = randomize.Struct(seed, o, serverStatusDBTypes, true, serverStatusColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ServerStatus struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := ServerStatusExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if ServerStatus exists: %s", err)
	}
	if !e {
		t.Errorf("Expected ServerStatusExists to return true, but got false.")
	}
}

func testServerStatusesFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ServerStatus{}
	if err = randomize.Struct(seed, o, serverStatusDBTypes, true, serverStatusColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ServerStatus struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	serverStatusFound, err := FindServerStatus(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if serverStatusFound == nil {
		t.Error("want a record, got nil")
	}
}

func testServerStatusesBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ServerStatus{}
	if err = randomize.Struct(seed, o, serverStatusDBTypes, true, serverStatusColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ServerStatus struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = ServerStatuses().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testServerStatusesOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ServerStatus{}
	if err = randomize.Struct(seed, o, serverStatusDBTypes, true, serverStatusColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ServerStatus struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := ServerStatuses().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testServerStatusesAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	serverStatusOne := &ServerStatus{}
	serverStatusTwo := &ServerStatus{}
	if err = randomize.Struct(seed, serverStatusOne, serverStatusDBTypes, false, serverStatusColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ServerStatus struct: %s", err)
	}
	if err = randomize.Struct(seed, serverStatusTwo, serverStatusDBTypes, false, serverStatusColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ServerStatus struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = serverStatusOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = serverStatusTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := ServerStatuses().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testServerStatusesCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	serverStatusOne := &ServerStatus{}
	serverStatusTwo := &ServerStatus{}
	if err = randomize.Struct(seed, serverStatusOne, serverStatusDBTypes, false, serverStatusColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ServerStatus struct: %s", err)
	}
	if err = randomize.Struct(seed, serverStatusTwo, serverStatusDBTypes, false, serverStatusColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ServerStatus struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = serverStatusOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = serverStatusTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := ServerStatuses().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func serverStatusBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *ServerStatus) error {
	*o = ServerStatus{}
	return nil
}

func serverStatusAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *ServerStatus) error {
	*o = ServerStatus{}
	return nil
}

func serverStatusAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *ServerStatus) error {
	*o = ServerStatus{}
	return nil
}

func serverStatusBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *ServerStatus) error {
	*o = ServerStatus{}
	return nil
}

func serverStatusAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *ServerStatus) error {
	*o = ServerStatus{}
	return nil
}

func serverStatusBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *ServerStatus) error {
	*o = ServerStatus{}
	return nil
}

func serverStatusAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *ServerStatus) error {
	*o = ServerStatus{}
	return nil
}

func serverStatusBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *ServerStatus) error {
	*o = ServerStatus{}
	return nil
}

func serverStatusAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *ServerStatus) error {
	*o = ServerStatus{}
	return nil
}

func testServerStatusesHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &ServerStatus{}
	o := &ServerStatus{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, serverStatusDBTypes, false); err != nil {
		t.Errorf("Unable to randomize ServerStatus object: %s", err)
	}

	AddServerStatusHook(boil.BeforeInsertHook, serverStatusBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	serverStatusBeforeInsertHooks = []ServerStatusHook{}

	AddServerStatusHook(boil.AfterInsertHook, serverStatusAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	serverStatusAfterInsertHooks = []ServerStatusHook{}

	AddServerStatusHook(boil.AfterSelectHook, serverStatusAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	serverStatusAfterSelectHooks = []ServerStatusHook{}

	AddServerStatusHook(boil.BeforeUpdateHook, serverStatusBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	serverStatusBeforeUpdateHooks = []ServerStatusHook{}

	AddServerStatusHook(boil.AfterUpdateHook, serverStatusAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	serverStatusAfterUpdateHooks = []ServerStatusHook{}

	AddServerStatusHook(boil.BeforeDeleteHook, serverStatusBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	serverStatusBeforeDeleteHooks = []ServerStatusHook{}

	AddServerStatusHook(boil.AfterDeleteHook, serverStatusAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	serverStatusAfterDeleteHooks = []ServerStatusHook{}

	AddServerStatusHook(boil.BeforeUpsertHook, serverStatusBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	serverStatusBeforeUpsertHooks = []ServerStatusHook{}

	AddServerStatusHook(boil.AfterUpsertHook, serverStatusAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	serverStatusAfterUpsertHooks = []ServerStatusHook{}
}

func testServerStatusesInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ServerStatus{}
	if err = randomize.Struct(seed, o, serverStatusDBTypes, true, serverStatusColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ServerStatus struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := ServerStatuses().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testServerStatusesInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ServerStatus{}
	if err = randomize.Struct(seed, o, serverStatusDBTypes, true); err != nil {
		t.Errorf("Unable to randomize ServerStatus struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(serverStatusColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := ServerStatuses().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testServerStatusToOneServerUsingServer(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local ServerStatus
	var foreign Server

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, serverStatusDBTypes, false, serverStatusColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ServerStatus struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, serverDBTypes, false, serverColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Server struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.ServerID = foreign.ID
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.Server().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.ID != foreign.ID {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	ranAfterSelectHook := false
	AddServerHook(boil.AfterSelectHook, func(ctx context.Context, e boil.ContextExecutor, o *Server) error {
		ranAfterSelectHook = true
		return nil
	})

	slice := ServerStatusSlice{&local}
	if err = local.L.LoadServer(ctx, tx, false, (*[]*ServerStatus)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Server == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.Server = nil
	if err = local.L.LoadServer(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Server == nil {
		t.Error("struct should have been eager loaded")
	}

	if !ranAfterSelectHook {
		t.Error("failed to run AfterSelect hook for relationship")
	}
}

func testServerStatusToOneSetOpServerUsingServer(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a ServerStatus
	var b, c Server

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, serverStatusDBTypes, false, strmangle.SetComplement(serverStatusPrimaryKeyColumns, serverStatusColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, serverDBTypes, false, strmangle.SetComplement(serverPrimaryKeyColumns, serverColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, serverDBTypes, false, strmangle.SetComplement(serverPrimaryKeyColumns, serverColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*Server{&b, &c} {
		err = a.SetServer(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.Server != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.ServerStatus != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.ServerID != x.ID {
			t.Error("foreign key was wrong value", a.ServerID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.ServerID))
		reflect.Indirect(reflect.ValueOf(&a.ServerID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.ServerID != x.ID {
			t.Error("foreign key was wrong value", a.ServerID, x.ID)
		}
	}
}

func testServerStatusesReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ServerStatus{}
	if err = randomize.Struct(seed, o, serverStatusDBTypes, true, serverStatusColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ServerStatus struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testServerStatusesReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ServerStatus{}
	if err = randomize.Struct(seed, o, serverStatusDBTypes, true, serverStatusColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ServerStatus struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := ServerStatusSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testServerStatusesSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ServerStatus{}
	if err = randomize.Struct(seed, o, serverStatusDBTypes, true, serverStatusColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ServerStatus struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := ServerStatuses().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	serverStatusDBTypes = map[string]string{`ID`: `uuid`, `ServerID`: `uuid`, `Health`: `text`, `State`: `text`, `Info`: `text`, `CreatedAt`: `timestamp with time zone`, `UpdatedAt`: `timestamp with time zone`}
	_                   = bytes.MinRead
)

func testServerStatusesUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(serverStatusPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(serverStatusAllColumns) == len(serverStatusPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &ServerStatus{}
	if err = randomize.Struct(seed, o, serverStatusDBTypes, true, serverStatusColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ServerStatus struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := ServerStatuses().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, serverStatusDBTypes, true, serverStatusPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize ServerStatus struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testServerStatusesSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(serverStatusAllColumns) == len(serverStatusPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &ServerStatus{}
	if err = randomize.Struct(seed, o, serverStatusDBTypes, true, serverStatusColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ServerStatus struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := ServerStatuses().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, serverStatusDBTypes, true, serverStatusPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize ServerStatus struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(serverStatusAllColumns, serverStatusPrimaryKeyColumns) {
		fields = serverStatusAllColumns
	} else {
		fields = strmangle.SetComplement(
			serverStatusAllColumns,
			serverStatusPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := ServerStatusSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testServerStatusesUpsert(t *testing.T) {
	t.Parallel()

	if len(serverStatusAllColumns) == len(serverStatusPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := ServerStatus{}
	if err = randomize.Struct(seed, &o, serverStatusDBTypes, true); err != nil {
		t.Errorf("Unable to randomize ServerStatus struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert ServerStatus: %s", err)
	}

	count, err := ServerStatuses().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, serverStatusDBTypes, false, serverStatusPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize ServerStatus struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert ServerStatus: %s", err)
	}

	count, err = ServerStatuses().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
